### ISSUE TITLE
Exception thrown in setup mark test as success even if it failed

### ISSUE THREAD

**Issue by dbryla** [anotherchrisberry/spock-retry#20]
Let me present scenario:

```
package no.spid.payment.acceptance.milestone.external;

import com.anotherchrisberry.spock.extensions.retry.RetryOnFailure;
import spock.lang.Specification;

@RetryOnFailure
class RetryTest extends Specification {

    def setup() {
        throw new RuntimeException("setup")
    }

    def test() {
        given:
        throw new RuntimeException("test")
    }
}
```

This test ends with success, because after exception is caught during test execution then ```RetryInterceptor``` is invoking setup method again but when exception is caught it's only increasing ```attempts``` which leads to marking test as success cause it isn't trying to execute test again and rethrow exception, because ```attempts <= retryMax``` is false.

**Comment by anotherchrisberry** [comment]
Thank you for calling this out and including a simple test case to reproduce. Should be fixed in 0.6.1 (https://bintray.com/anotherchrisberry/spock-retry/spock-retry/0.6.1)
