### ISSUE TITLE
Project is not on JCenter

### ISSUE THREAD

**Issue by renatoathaydes** [anotherchrisberry/spock-retry#8]
Hi!

I would really love to use this but you don't seem to have published the artifacts on JCenter (or Maven Central) so it's hard to get your library automatically with Maven/Gradle.

Would you be able to push this to JCenter? As you already have the project on Bintray, it should be trivial to do that.

This [page](https://bintray.com/docs/usermanual/uploads/uploads_includingyourpackagesinjcenter.html) explains how to do it.

Regards.

**Comment by anotherchrisberry** [comment]
Sorry for the delay - I just pushed a new version to Bintray and included the sources jar. I will update this issue when it becomes available.

**Comment by anotherchrisberry** [comment]
Okay, should be available on jcenter now - https://bintray.com/bintray/jcenter?filterByPkgName=spock-retry

**Comment by renatoathaydes** [comment]
Thanks!
